---

- name: Test
  command: echo {{ maint_plan_id }} {{ infrastructure_id }}

- name: Download Playbooks for Maintenance Plan
  uri:
    url:  https://access.redhat.com/r/insights/v3/maintenance/{{ maint_plan_id }}/playbook 
    method: GET
    user: "{{ username }}"
    password: "{{ password }}"
    force_basic_auth: yes
    status_code: 200
    dest: myplaybook.yaml
  register: output2

- name: Download Test
  get_url:
    url: https://access.redhat.com/r/insights/v3/maintenance/{{ maint_plan_id }}/playbook
    url_username: "{{ username }}"
    url_password: "{{ password }}
    force_basic_auth: yes
    status_code: 200
    dest: myplaybook.yaml
    mode: 0440
