---

- name: Test
  command: echo {{ maint_plan_id }} {{ infrastructure_id }}

- name: Download Playbooks for Maintenance Plan
  uri:
    url:  https://access.redhat.com/r/insights/v3/maintenance/{{ maint_plan_id }}/playbook 
    method: GET
    user: "{{ username }}"
    password: "{{ password }}"
    force_basic_auth: yes
    creates: myplaybook.yaml
    dest: /opt/tmp

- name: Second Test
  get_url:
    url:  https://access.redhat.com/r/insights/v3/maintenance/{{ maint_plan_id }}/playbook
    dest: /opt/tmp/myplaybook.yaml
    force_basic_auth: yes
    url_username: "{{ username }}"
    url_password: "{{ password }}"
    force: yes
