---

- name: Create Github Repo
  uri:
    url: https://api.github.com/orgs/strategicdesignteam/repos
    force_basic_auth: yes
    become: true
    method: POST
    user: "{{ git_username }}"
    password: "{{ git_password }}"
    body_format: json
    status_code: 201
    headers:
       Content-Type: "application/json"
    body: 
      name: insights_for_{{ infrastructure_id }}
  register: output

- name: clone git repo
  command: git clone https://github.com/strategicdesignteam/insights_for_{{ infrastructure_id }}.git /opt/tmp/insights_plan_{{ infrastructure_id }}

- name: Download Playbooks for Maintenance Plan
  uri:
    url:  https://access.redhat.com/r/insights/v3/maintenance/{{ maint_plan_id }}/playbook
    become: true
    method: GET
    user: "{{ rh_username }}"
    password: "{{ rh_password }}"
    force_basic_auth: yes
    creates: myplaybook.yaml
    dest: /opt/tmp/insights_plan_{{ infrastructure_id }}

- name: Rename playbook
  command: mv /opt/tmp/insights_plan_{{ infrastructure_id }}/playbook /opt/tmp/insights_plan_{{ infrastructure_id }}/playbook.yaml
  

- name: Add files to git
  command: git add playbook.yaml
  args:
    chdir: /opt/tmp/insights_plan_{{ infrastructure_id }}

- name: Commit
  command: git commit -m "Adding playbook"
  args:
    chdir: /opt/tmp/insights_plan_{{ infrastructure_id }}

- name: Sleep just in case
  command: sleep 3

- name: Push files to git
  command: git push https://{{ git_username }}:{{ git_password }}@github.com/strategicdesignteam/insights_for_{{ infrastructure_id }}.git master
  args:
    chdir: /opt/tmp/insights_plan_{{ infrastructure_id }}

- name: Create project in Tower
  tower_project:
    name: insights_for_{{ infrastructure_id }}
    description: "insights for infrastructure"
    organization: "Default"
    scm_url: https://github.com/strategicdesignteam/insights_for_{{ infrastructure_id }}.git
    scm_type: git
    scm_branch: master
    scm_update_on_launch: true
    state: present
    tower_config_file: "~/.tower_cli.cfg"

- name: Sync project
  command: tower-cli project update -n insights_for_{{ infrastructure_id }} 

- name: Sleep just in case
  command: sleep 6

- name: Create openshift-ansible-contrib job template
  tower_job_template:
    name: insights_for_{{ infrastructure_id }}
    job_type: run
    inventory: aws-inventory
    project: insights_for_{{ infrastructure_id }}
    playbook: "playbook.yaml"
    machine_credential: aws-privkey
    cloud_credential: ec2
    state: present
    tower_config_file: "~/.tower_cli.cfg"

- name: Launch a job
  command:  tower-cli job launch -J insights_for_{{ infrastructure_id }}
